Wrong shot number:
[3, 9, 8]

Correct shot number:
[2]

Raw json:

{'hasError': True, 'errParameter': ['dfs.image.transfer.bandwidthPerSec'], 'reason': ["The property 'dfs.image.transfer.bandwidthPerSec' has the value '0' which is not within the accepted range of 1 to 1073741824."]}

{'hasError': False, 'errParameter': [], 'reason': []}

{'hasError': True, 'errParameter': ['dfs.client.datanode-restart.timeout'], 'reason': ["The property 'dfs.client.datanode-restart.timeout' has the value '60s' which exceeds the range of an Integer."]}

Raw json:

{'hasError': False, 'errParameter': [], 'reason': []}

{'hasError': True, 'errParameter': ['dfs.client.datanode-restart.timeout'], 'reason': ["The property 'dfs.client.datanode-restart.timeout' has the value '60s' which exceeds the range of an Integer."]}

{'hasError': True, 'errParameter': ['dfs.blocksize'], 'reason': ["The property 'dfs.blocksize' has the value '67108864' which exceeds the range of an Integer."]}

Raw json:

{'hasError': True, 'errParameter': ['dfs.mover.movedWinWidth'], 'reason': ["The property 'dfs.mover.movedWinWidth' has the value '2700000' which exceeds the range of an Integer."]}

{'hasError': True, 'errParameter': ['dfs.image.transfer.bandwidthPerSec'], 'reason': ["The property 'dfs.image.transfer.bandwidthPerSec' has the value '0' which is not within the accepted range of [1, 1073741824]."]}

{'hasError': True, 'errParameter': ['dfs.image.transfer.bandwidthPerSec'], 'reason': ["The property 'dfs.image.transfer.bandwidthPerSec' has the value '0' which is not within the accepted range of [1, 1073741824]."]}

Final result:

There are 1 misconfiguration parameters in the input: dfs.image.transfer.bandwidthPerSec
[Ciri] Reason for dfs.image.transfer.bandwidthPerSec: The property 'dfs.image.transfer.bandwidthPerSec' has the value '0' which is not within the accepted range of [1, 1073741824].
