Wrong shot number:
[8, 13, 6]

Correct shot number:
[7]

Raw json:

{'hasError': True, 'errParameter': ['alluxio.underfs.hdfs.remote'], 'reason': ["The property 'alluxio.underfs.hdfs.remote' has the value 'true' which is not within the accepted value {true,false}."]}

{'hasError': True, 'errParameter': ['alluxio.underfs.hdfs.remote'], 'reason': ["The property 'alluxio.underfs.hdfs.remote' has the value 'true' which is not within the accepted value {true,false}."]}

{'hasError': True, 'errParameter': ['alluxio.worker.tieredstore.level1.dirs.path'], 'reason': ["The property 'alluxio.worker.tieredstore.level1.dirs.path' has the value '/valid/file2' which does not exist."]}

Final result:

There are 1 misconfiguration parameters in the input: alluxio.underfs.hdfs.remote
[Ciri] Reason for alluxio.underfs.hdfs.remote: The property 'alluxio.underfs.hdfs.remote' has the value 'true' which is not within the accepted value {true,false}.
