Wrong shot number:
[7, 10, 5]

Correct shot number:
[7]

Raw json:

{'hasError': True, 'errParameter': ['fs.ftp.data.connection.mode'], 'reason': ["The property 'fs.ftp.data.connection.mode' has the value 'ACTIVE_LOCAL_DATA_CONNECTION_MODE' which is not within the accepted values {ACTIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_REMOTE_DATA_CONNECTION_MODE}."]}

{'hasError': True, 'errParameter': ['fs.ftp.data.connection.mode'], 'reason': ["The property 'fs.ftp.data.connection.mode' has the value 'ACTIVE_LOCAL_DATA_CONNECTION_MODE' which is not a valid value. Valid values are ACTIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_LOCAL_DATA_CONNECTION_MODE, and PASSIVE_REMOTE_DATA_CONNECTION_MODE."]}

{'hasError': True, 'errParameter': ['fs.ftp.data.connection.mode'], 'reason': ["The property 'fs.ftp.data.connection.mode' has the value 'ACTIVE_LOCAL_DATA_CONNECTION_MODE' which is not within the accepted values {ACTIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_REMOTE_DATA_CONNECTION_MODE}."]}

Final result:

There are 1 misconfiguration parameters in the input: fs.ftp.data.connection.mode
[Ciri] Reason for fs.ftp.data.connection.mode: The property 'fs.ftp.data.connection.mode' has the value 'ACTIVE_LOCAL_DATA_CONNECTION_MODE' which is not within the accepted values {ACTIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_LOCAL_DATA_CONNECTION_MODE, PASSIVE_REMOTE_DATA_CONNECTION_MODE}.
