Raw json:

{'hasError': True, 'errParameter': ['dfs.datanode.http.internal-proxy.port'], 'reason': ['dfs.datanode.http.internal-proxy.port is not a valid port number']}

{'hasError': True, 'errParameter': ['dfs.datanode.http.internal-proxy.port'], 'reason': ['dfs.datanode.http.internal-proxy.port is not a valid port number.']}

{'hasError': True, 'errParameter': ['dfs.datanode.http.internal-proxy.port'], 'reason': ['dfs.datanode.http.internal-proxy.port is not a valid port number.']}

Final result:

There are 1 misconfiguration parameters in the input: dfs.datanode.http.internal-proxy.port
[Ciri] Reason for dfs.datanode.http.internal-proxy.port: dfs.datanode.http.internal-proxy.port is not a valid port number.
