Wrong shot number:
[1, 6, 5]

Correct shot number:
[3]

Raw json:

{'hasError': True, 'errParameter': ['PASSWORD_HASHERS'], 'reason': ["The property 'PASSWORD_HASHERS' has the value '['django.contrib.auth.hashers.PBKDF2PasswordHasher','django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher','django.contrib.auth.hashers.Argon2PasswordHasher','django.contrib.auth.hashers.BCryptSHA256PasswordHasher','django.contrib.auth.hashers.ScryptPasswordHasher']' which is not of the correct type List."]}

{'hasError': False, 'errParameter': [], 'reason': []}

{'hasError': True, 'errParameter': ['PASSWORD_HASHERS'], 'reason': ["The property 'PASSWORD_HASHERS' has the value '['django.contrib.auth.hashers.PBKDF2PasswordHasher','django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher','django.contrib.auth.hashers.Argon2PasswordHasher','django.contrib.auth.hashers.BCryptSHA256PasswordHasher','django.contrib.auth.hashers.ScryptPasswordHasher']' which is not of the correct type List."]}

Final result:

There are 1 misconfiguration parameters in the input: PASSWORD_HASHERS
[Ciri] Reason for PASSWORD_HASHERS: The property 'PASSWORD_HASHERS' has the value '['django.contrib.auth.hashers.PBKDF2PasswordHasher','django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher','django.contrib.auth.hashers.Argon2PasswordHasher','django.contrib.auth.hashers.BCryptSHA256PasswordHasher','django.contrib.auth.hashers.ScryptPasswordHasher']' which is not of the correct type List.
