Raw json:

{'hasError': True, 'errParameter': ['fs.s3a.proxy.port', 'hadoop.caller.context.max.size'], 'reason': ["The value for 'fs.s3a.proxy.port' should be a valid port number.", "The description for 'hadoop.caller.context.max.size' is not properly formatted."]}

{'hasError': True, 'errParameter': ['fs.s3a.proxy.port', 'hadoop.caller.context.max.size'], 'reason': ["Value for property 'fs.s3a.proxy.port' should be a valid port number.", "Value for property 'hadoop.caller.context.max.size' should be a positive integer."]}

{'hasError': True, 'errParameter': ['fs.s3a.proxy.port', 'hadoop.caller.context.max.size'], 'reason': ["Value for property 'fs.s3a.proxy.port' should be a valid port number.", "Value for property 'hadoop.caller.context.max.size' should be a positive integer."]}

Final result:

There are 2 misconfiguration parameters in the input: fs.s3a.proxy.port	hadoop.caller.context.max.size
[Ciri] Reason for fs.s3a.proxy.port: Value for property 'fs.s3a.proxy.port' should be a valid port number.
[Ciri] Reason for hadoop.caller.context.max.size: Value for property 'hadoop.caller.context.max.size' should be a positive integer.
