Wrong shot number:
[6, 11, 12]

Correct shot number:
[16]

Raw json:

{'hasError': False, 'errParameter': [], 'reason': []}

{'hasError': True, 'errParameter': ['dfs.webhdfs.rest-csrf.browser-useragents-regex'], 'reason': ["The property 'dfs.webhdfs.rest-csrf.browser-useragents-regex' has the value '^Opera.*' which is not a valid regular expression."]}

{'hasError': True, 'errParameter': ['dfs.webhdfs.socket.connect-timeout'], 'reason': ["The property 'dfs.webhdfs.socket.connect-timeout' has the value '60s' which is out of the valid range of a time unit."]}

Raw json:

{'hasError': True, 'errParameter': ['dfs.webhdfs.socket.connect-timeout'], 'reason': ["The property 'dfs.webhdfs.socket.connect-timeout' has the value '60s' which is out of the valid range of a time unit."]}

{'hasError': True, 'errParameter': ['dfs.namenode.gc.time.monitor.observation.window.ms'], 'reason': ["The property 'dfs.namenode.gc.time.monitor.observation.window.ms' has the value '2m' which is out of the valid range of a time unit."]}

{'hasError': True, 'errParameter': ['dfs.webhdfs.socket.connect-timeout'], 'reason': ["The property 'dfs.webhdfs.socket.connect-timeout' has the value '60s' which does not follow the correct time format."]}

Final result:

There are 1 misconfiguration parameters in the input: dfs.webhdfs.socket.connect-timeout
[Ciri] Reason for dfs.webhdfs.socket.connect-timeout: The property 'dfs.webhdfs.socket.connect-timeout' has the value '60s' which is out of the valid range of a time unit.
